# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_param simulator.modelsimInstallPath C:/ProgramData/modeltech64_10.1c/win64
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir K:/xilinx/LocationP2/Location.cache/wt [current_project]
set_property parent.project_path K:/xilinx/LocationP2/Location.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_ip -quiet K:/xilinx/LocationP2/Location.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci
set_property used_in_implementation false [get_files -all k:/xilinx/LocationP2/Location.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0/fifo_generator_0.xdc]
set_property is_locked true [get_files K:/xilinx/LocationP2/Location.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci]

read_verilog -library xil_defaultlib {
  K:/xilinx/LocationP2/Location.srcs/sources_1/new/frevDiv.v
  K:/xilinx/LocationP2/Location.srcs/sources_1/new/TOP.v
  K:/xilinx/LocationP2/Location.srcs/sources_1/new/uart_tx_2.v
  K:/xilinx/LocationP2/Location.srcs/sources_1/new/uartone.v
  K:/xilinx/LocationP2/Location.srcs/sources_1/new/DSM.v
  K:/xilinx/LocationP2/Location.srcs/sources_1/new/ControlUnit.v
  K:/xilinx/LocationP2/Location.srcs/sources_1/new/MasterCHIP.v
  K:/xilinx/LocationP2/Location.srcs/sources_1/new/design.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc K:/xilinx/LocationP2/Location.srcs/constrs_1/new/Basys3.xdc
set_property used_in_implementation false [get_files K:/xilinx/LocationP2/Location.srcs/constrs_1/new/Basys3.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top topdesign -part xc7a35tcpg236-1


write_checkpoint -force -noxdef topdesign.dcp

catch { report_utilization -file topdesign_utilization_synth.rpt -pb topdesign_utilization_synth.pb }
